### ISSUE TITLE
Result tab summary is blank when not active

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/analyzer#5]
Steps to reproduce:

1. String Disease query: breast cancer
2. Note that a STRING tab is created and active
3. Run Analyze Network

Obs: Analyzer tab is created, but not active. And when you go to it, it is blank!
Exp: Make is active upon creation and then fill with summary info

After making active and running again on another networks, then it works fine. It's just a problem with the first-time use when another tab is already in Results panel.

**Comment by AdamStuart** [comment]
There is no SessionClosedEvent, just SessionLoadedEvent.  Since a close opens another new session, this should be equivalent.

**Comment by AdamStuart** [comment]
seems to be working fine now
