### ISSUE TITLE
Closing the session should unregister the results panel

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/analyzer#6]
You had asked if the results panel ever needed to be _unregistered_. Analogous to other apps like scNetViz, we should probably unregister as session close. That way the panel isn't there fo all subsequent sessions.

**Comment by AlexanderPico** [comment]
http://chianti.ucsd.edu/cytoscape-3.6.0/API/org/cytoscape/application/CyShutdown.html

**Comment by scootermorris** [comment]
The CyShutdown event is called when Cytoscape exits.  I think what you probably want is to listen for the SessionLoadedEvent.  When you do a close, interestingly, it actually opens a new empty session.

**Comment by AdamStuart** [comment]
fixed
